"""reservas y wishlist_config

Revision ID: 264cedb6c13a
Revises: 720542e7ae79
Create Date: 2026-08-09 09:25:28.477676

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '264cedb6c13a'
down_revision: Union[str, None] = '720542e7ae79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlist_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('share_token', sa.String(length=36), nullable=False),
    sa.Column('nombre_app', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('nombre_reservante', sa.String(length=255), nullable=False),
    sa.Column('token_deshacer', sa.String(length=36), nullable=False),
    sa.Column('revelado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_deshacer')
    )
    op.create_index(op.f('ix_reservas_item_id'), 'reservas', ['item_id'], unique=False)
    op.create_index('uq_reservas_item_activa', 'reservas', ['item_id'], unique=True, postgresql_where='released_at IS NULL')
    # Seed: la fila única de configuración debe existir desde el primer
    # arranque para que GET /config funcione sin pasos manuales.
    op.execute(
        sa.text(
            "INSERT INTO wishlist_config (share_token, nombre_app) "
            "VALUES (:token, 'Julia en Camino')"
        ).bindparams(token=str(uuid.uuid4()))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_reservas_item_activa', table_name='reservas', postgresql_where='released_at IS NULL')
    op.drop_index(op.f('ix_reservas_item_id'), table_name='reservas')
    op.drop_table('reservas')
    op.drop_table('wishlist_config')
    # ### end Alembic commands ###
