"""items y fotos_item

Revision ID: 720542e7ae79
Revises: 9e30edb1d7c3
Create Date: 2026-08-09 09:24:58.804849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '720542e7ae79'
down_revision: Union[str, None] = '9e30edb1d7c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=True),
    sa.Column('amazon_link', sa.String(length=2000), nullable=True),
    sa.Column('estado', sa.Enum('NECESITADO', 'RESERVADO', 'ADQUIRIDO', name='estadoitem'), nullable=False),
    sa.Column('origen_adquisicion', sa.Enum('NOSOTROS', 'REGALO', name='origenadquisicion'), nullable=True),
    sa.Column('gifter_name', sa.String(length=255), nullable=True),
    sa.Column('caja_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['caja_id'], ['cajas_almacenamiento.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_estado'), 'items', ['estado'], unique=False)
    op.create_table('fotos_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fotos_item_item_id'), 'fotos_item', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fotos_item_item_id'), table_name='fotos_item')
    op.drop_table('fotos_item')
    op.drop_index(op.f('ix_items_estado'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
